### ISSUE TITLE
Unable to update 

### ISSUE THREAD

**Issue by mrcnpp** [swisskyrepo/Wordpresscan#23]
Hi i'm unable to update the wordpress scanner
the error is down below 
i think the main problem is this : `gzip: database/user-agents.txt.gz: not in gzip format`
Thnks for the hel my machine : ubutnu 18.04 ,x64
```bash
$ python wordpresscan.py -u"http://social.ford.it"  --update --random-agent
_______________________________________________________________ 
 _    _               _                                         
| |  | |             | |                                        
| |  | | ___  _ __ __| |_ __  _ __ ___  ___ ___  ___ __ _ _ __  
| |/\| |/ _ \| '__/ _` | '_ \| '__/ _ \/ __/ __|/ __/ _` | '_ \ 
\  /\  / (_) | | | (_| | |_) | | |  __/\__ \__ \ (_| (_| | | | |
 \/  \/ \___/|_|  \__,_| .__/|_|  \___||___/___/\___\__,_|_| |_|
                       | |                                      
                       |_|                                      
 WordPress scanner based on wpscan work - @pentest_swissky      
_______________________________________________________________ 
Updating database - Last update: Tue Oct  9 12:33:59 2018
	Downloading local_vulnerable_files.xml File updated !
	Downloading local_vulnerable_files.xsd File updated !
	Downloading timthumbs.txt File updated !
	Downloading user-agents.txt File updated !
	Downloading wp_versions.xml File updated !
	Downloading wp_versions.xsd File updated !
	Downloading wordpresses.json File updated !
	Downloading plugins.json File updated !
	Downloading themes.json File updated !
	Downloaded : 1.45 Mo
gzip: database/user-agents.txt.gz: not in gzip format

gzip: database/timthumbs.txt.gz: not in gzip format
[+] URL: http://social.ford.it
Traceback (most recent call last):
  File "wordpresscan.py", line 53, in <module>
    wp = Wordpress(format_url(results.url), results.random_agent, results.nocheck, results.max_threads)
  File "/home/marco/Desktop/burp/Wordpresscan-master/engine/wordpress.py", line 24, in __init__
    self.random_agent()
  File "/home/marco/Desktop/burp/Wordpresscan-master/engine/wordpress.py", line 55, in random_agent
    with open('database/user-agents.txt','r') as f:
IOError: [Errno 2] No such file or directory: 'database/user-agents.txt'

```

**Comment by swisskyrepo** [comment]
Hi, 
Thank you for the issue, this is patched in the latest commit https://github.com/swisskyrepo/Wordpresscan/commit/dd794cfcea300689a4c6874cc62e7dc48972fc1d :)

**Comment by mrcnpp** [comment]
Hi, 
Thanks for the fast patch :+1:
