### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by rdek** [swisskyrepo/Wordpresscan#30]
Hi Swissky!
Thanks for the awesome tool, unfortunately I've struggling with JSON parse error like:

```
/> ./wordpresscan.py -u "http://scannedsite.org/" --random-agent
...
[!] WordPress version 4.1 identified from advanced fingerprinting
Traceback (most recent call last):
  File "./wordpresscan.py", line 62, in <module>
    Scan_Engine(wp, results.aggressive)
  File "/opt/Wordpresscan/engine/scan.py", line 16, in __init__
    self.list_wp_version_vulnerabilities(wordpress, "wordpresses")
  File "/opt/Wordpresscan/engine/scan.py", line 106, in list_wp_version_vulnerabilities
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Software obtained thru git clone https://github.com/swisskyrepo/Wordpresscan
python version: 2.7.16+
Any ideas?

**Comment by truesamurai** [comment]
I am having the same error. I do have some results from the scan but at some part the error pops up.

**Comment by slekiz** [comment]
same error to...
