### ISSUE TITLE
error No JSON object could be decoded

### ISSUE THREAD

**Issue by truesamurai** [swisskyrepo/Wordpresscan#33]
When I do a scan I get some results, but then this error pops up:
I am on Kali version 2019.4.

Traceback (most recent call last):
  File "wordpresscan.py", line 62, in <module>
    Scan_Engine(wp, results.aggressive)
  File "/opt/Wordpresscan/engine/scan.py", line 16, in __init__
    self.list_wp_version_vulnerabilities(wordpress, "wordpresses")
  File "/opt/Wordpresscan/engine/scan.py", line 106, in list_wp_version_vulnerabilities
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by slekiz** [comment]
I have same problem...

**Comment by Fa2y** [comment]
Wpscan changed the filenames of there db so when wordpressscan is fetching the old file, it's just getting Cloudflare errors, I guess the whole scan process should be updated.
(This is from wpscan updater)

> class Updater
>    \#/!\ Might want to also update the Enumeration\#cli_options when some filenames are changed here
>       FILES = %w[
>         metadata.json wp_fingerprints.json
>         timthumbs-v3.txt config_backups.txt db_exports.txt
>         dynamic_finders.yml LICENSE sponsor.txt
>       ].freeze
> 
>       OLD_FILES = %w[
>         wordpress.db user-agents.txt dynamic_finders_01.yml
>         wordpresses.json plugins.json themes.json
>       ].freeze

**Comment by EranGoldman** [comment]
How to fix it :
1. Go to databases folder
2. delete all json files (themes.json , plugins.json, wordpresses.json)
3. download them again from the repo
