### ISSUE TITLE
Script broken

### ISSUE THREAD

**Issue by mnglitam** [swisskyrepo/Wordpresscan#47]
I am getting this error

File "D:\pentest\Wordpresscan\main.py", line 15
    print "_______________________________________________________________ "
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("_______________________________________________________________ ")?

**Comment by adrianratajczak** [comment]
Same here on Windows

**Comment by adrianratajczak** [comment]
Another error
`Traceback (most recent call last):
  File "wordpresscan.py", line 6, in <module>
    from engine.core import *
  File "C:\scan\engine\core.py", line 65
    print "\033[93mUpdating database\033[92m - Last update: \033[0m" + database_last_date('database/local_vulnerable_files.xml')
                                                                   ^
SyntaxError: invalid syntax`
