### ISSUE TITLE
Error - Enumerating plugins from passive detection

### ISSUE THREAD

**Issue by fcafra** [swisskyrepo/Wordpresscan#8]
cmd:
python main.py -u "http://WWW.SITE.EXAMPLE" --update --random-agent

StackTrace:
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    Scan_Engine(wp, results.aggressive)
  File "/home/App/Wordpresscan/engine/scan.py", line 19, in __init__
    self.enumerating_plugins_passive(wordpress)
  File "/home/App/Wordpresscan/engine/scan.py", line 188, in enumerating_plugins_passive
    display_vulnerable_component(plugin_name, plugin_version, "plugins")
  File "/home/App/Wordpresscan/engine/core.py", line 182, in display_vulnerable_component
    if is_lower(version, data[name]['latest_version'], False):  
  File "/home/App/Wordpresscan/engine/core.py", line 144, in is_lower
    if len(str_two) < 5:
TypeError: object of type 'NoneType' has no len()

**Comment by mpvillafranca** [comment]
Got same error while scanning plugin: "Name: js_composer - v5.1.1".

**Comment by swisskyrepo** [comment]
Hello, 
Could you try with the new version ? :)
If the problem persists can you provide the full result of Wordpresscan (with a redacted URL if it's not local ^^)

**Comment by fcafra** [comment]
Thank's, now it seems to working ...
